name = "CSAVEinJulia"
uuid = "56894a01-51d8-47a5-a1b2-a4f35f317d29"
version = "0.1.0"
authors = ["Yen-Heng Henry Chen <chenyh@mit.edu>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MPSGE = "d5dc2f44-7ae2-49e9-bc77-b47b6bca565d"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Ipopt = "1.13.0"
JLD2 = "0.6.2"
JuMP = "1.29.3"
MPSGE = "0.6.4"
NamedArrays = "0.10.5"
